const express=require('express');
const router=express.Router();
const c=require('../controllers/competitor.controller');
const auth=require('../middleware/auth.middleware');
router.post('/projects/:projectId/competitors',auth,c.createCompetitor);
router.get('/projects/:projectId/competitors',auth,c.getCompetitors);
router.get('/projects/:projectId/seo/competitors/intelligence',auth,c.getCompetitorIntelligence);
router.get('/projects/:projectId/seo/competitors/provider-status',auth,c.getCompetitorProviderStatus);
router.post('/projects/:projectId/seo/competitors/sync',auth,c.syncCompetitorData);
router.post('/projects/:projectId/seo/backlink-opportunities',auth,c.createOpportunity);
router.put('/projects/:projectId/seo/backlink-opportunities/:id',auth,c.updateOpportunity);
router.delete('/projects/:projectId/seo/backlink-opportunities/:id',auth,c.deleteOpportunity);
router.get('/competitors/:id',auth,c.getCompetitorById);
router.put('/competitors/:id',auth,c.updateCompetitor);
router.delete('/competitors/:id',auth,c.deleteCompetitor);
router.post('/competitors/:competitorId/keywords',auth,c.createCompetitorKeyword);
router.put('/competitors/:competitorId/keywords/:id',auth,c.updateCompetitorKeyword);
router.delete('/competitors/:competitorId/keywords/:id',auth,c.deleteCompetitorKeyword);
router.post('/competitors/:competitorId/backlinks',auth,c.createCompetitorBacklink);
router.put('/competitors/:competitorId/backlinks/:id',auth,c.updateCompetitorBacklink);
router.delete('/competitors/:competitorId/backlinks/:id',auth,c.deleteCompetitorBacklink);
module.exports=router;
