const express=require('express');
const router=express.Router();
const c=require('../controllers/competitor.controller');
const auth=require('../middleware/auth.middleware');
router.post('/projects/:projectId/competitors',auth,c.createCompetitor);
router.get('/projects/:projectId/competitors',auth,c.getCompetitors);
router.get('/projects/:projectId/seo/competitors/intelligence',auth,c.getCompetitorIntelligence);
router.post('/projects/:projectId/seo/backlink-opportunities',auth,c.createOpportunity);
router.get('/competitors/:id',auth,c.getCompetitorById);
router.put('/competitors/:id',auth,c.updateCompetitor);
router.delete('/competitors/:id',auth,c.deleteCompetitor);
router.post('/competitors/:competitorId/keywords',auth,c.createCompetitorKeyword);
router.post('/competitors/:competitorId/backlinks',auth,c.createCompetitorBacklink);
module.exports=router;
