const express=require('express');
const auth=require('../middleware/auth.middleware');
const c=require('../controllers/googleAnalytics4.controller');
const router=express.Router();
router.get('/projects/:projectId/ga4/connect',auth,c.connect);
router.get('/projects/:projectId/ga4/status',auth,c.status);
router.get('/projects/:projectId/ga4/properties',auth,c.properties);
router.post('/projects/:projectId/ga4/property',auth,c.selectProperty);
router.get('/projects/:projectId/ga4/report',auth,c.report);
router.get('/ga4/callback',c.callback);
module.exports=router;
